# Generated by Django 3.2.6 on 2021-09-21 04:20

import apps.device.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20210920_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Old price'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default=10000, max_length=20, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(upload_to=apps.device.models.get_upload_to, verbose_name='Image'),
        ),
    ]
