# Generated by Django 3.2.6 on 2021-09-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_auto_20210921_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='content_uz',
        ),
        migrations.AddField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Is popular'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_content',
            field=models.TextField(default=1, verbose_name='Main Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='main_content_en',
            field=models.TextField(null=True, verbose_name='Main Content'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_content_ru',
            field=models.TextField(null=True, verbose_name='Main Content'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_content_uz',
            field=models.TextField(null=True, verbose_name='Main Content'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_content',
            field=models.TextField(blank=True, null=True, verbose_name='Secondary Content'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Secondary Content'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Secondary Content'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_content_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Secondary Content'),
        ),
        migrations.AddField(
            model_name='product',
            name='trend',
            field=models.IntegerField(blank=True, choices=[(0, 'Internet'), (1, 'Camera'), (2, 'Telephony'), (3, 'IPTV'), (4, 'Device'), (5, 'Montage'), (6, 'Design'), (7, 'Development')], null=True, verbose_name='Trend'),
        ),
    ]
