# Generated by Django 3.2.6 on 2021-09-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_alter_product_trend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='request',
            name='last_name',
        ),
        migrations.AddField(
            model_name='request',
            name='message',
            field=models.TextField(default=1, verbose_name='Message'),
            preserve_default=False,
        ),
    ]
