# Generated by Django 3.2.6 on 2021-10-01 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_auto_20210922_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'parent_category__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='device.category', verbose_name='Parent Category'),
        ),
    ]
