# Generated by Django 3.2.6 on 2021-10-28 07:14

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0009_alter_category_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_content',
            field=djrichtextfield.models.RichTextField(verbose_name='Main Content'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_content_en',
            field=djrichtextfield.models.RichTextField(null=True, verbose_name='Main Content'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_content_ru',
            field=djrichtextfield.models.RichTextField(null=True, verbose_name='Main Content'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_content_uz',
            field=djrichtextfield.models.RichTextField(null=True, verbose_name='Main Content'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondary_content',
            field=djrichtextfield.models.RichTextField(blank=True, null=True, verbose_name='Secondary Content'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondary_content_en',
            field=djrichtextfield.models.RichTextField(blank=True, null=True, verbose_name='Secondary Content'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondary_content_ru',
            field=djrichtextfield.models.RichTextField(blank=True, null=True, verbose_name='Secondary Content'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondary_content_uz',
            field=djrichtextfield.models.RichTextField(blank=True, null=True, verbose_name='Secondary Content'),
        ),
    ]
