# Generated by Django 3.2.6 on 2021-09-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_auto_20210920_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='global_speed',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='tasix_speed',
        ),
        migrations.AddField(
            model_name='tariff',
            name='speed_or_minutes',
            field=models.CharField(default=1, max_length=50, verbose_name='Internet speed or minutes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariff',
            name='tas_ix',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tas Ix'),
        ),
        migrations.AlterField(
            model_name='homearea',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Home name'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price_cash12',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Monthly price for 12 months'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price_cash6',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Monthly price for 6 months'),
        ),
    ]
