# Generated by Django 3.2.6 on 2021-09-20 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_auto_20210920_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='home',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='provider.homearea', verbose_name='Home'),
            preserve_default=False,
        ),
    ]
