# Generated by Django 3.2.6 on 2021-09-20 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_request_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='cameras', verbose_name='Main image (square)')),
                ('image2', models.ImageField(upload_to='cameras', verbose_name='Secondary image (album)')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=50, null=True, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('content_en', models.TextField(null=True, verbose_name='Content')),
                ('content_ru', models.TextField(null=True, verbose_name='Content')),
                ('content_uz', models.TextField(null=True, verbose_name='Content')),
                ('price', models.CharField(max_length=50, verbose_name='Price')),
                ('is_main', models.BooleanField(default=False, help_text='to view on web page', verbose_name='Is main')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': '11. Cameras',
            },
        ),
        migrations.CreateModel(
            name='TypeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=50, null=True, verbose_name='Title')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
            options={
                'verbose_name': 'Type Channel',
                'verbose_name_plural': '9. Type Channels',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='channels', verbose_name='Channel image')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=50, null=True, verbose_name='Title')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('type_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.typechannel', verbose_name='Type channel')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': '10. Channels',
            },
        ),
    ]
