# Generated by Django 3.2.6 on 2021-09-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0007_auto_20210920_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Tariff title')),
                ('speed', models.CharField(max_length=50, verbose_name='Internet speed')),
                ('tas_ix', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tas Ix speed')),
                ('price', models.CharField(max_length=20, verbose_name='Monthly price')),
                ('price_cash6', models.CharField(blank=True, max_length=20, null=True, verbose_name='Monthly price for 6 months')),
                ('price_cash12', models.CharField(blank=True, max_length=20, null=True, verbose_name='Monthly price for 12 months')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
            options={
                'verbose_name': 'Internet tariff',
                'verbose_name_plural': '2. Internet tariffs',
            },
        ),
        migrations.CreateModel(
            name='TelephonyTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Tariff title')),
                ('minutes', models.CharField(max_length=50, verbose_name='Minutes')),
                ('price', models.CharField(max_length=20, verbose_name='Monthly price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
            options={
                'verbose_name': 'Telephony tariff',
                'verbose_name_plural': '3. Telephony tariffs',
            },
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.AlterModelOptions(
            name='cabletech',
            options={'verbose_name': 'Cable Technology', 'verbose_name_plural': '4.2. Cable Technologies'},
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': 'Channel', 'verbose_name_plural': '6.1. Channels'},
        ),
        migrations.AlterModelOptions(
            name='cityarea',
            options={'verbose_name': 'City Area', 'verbose_name_plural': '4. City Areas'},
        ),
        migrations.AlterModelOptions(
            name='districtarea',
            options={'verbose_name': 'District Area', 'verbose_name_plural': '4.1. District Areas'},
        ),
        migrations.AlterModelOptions(
            name='homearea',
            options={'verbose_name': 'Home Area', 'verbose_name_plural': '4.4. Home Areas'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Request', 'verbose_name_plural': '5. Requests'},
        ),
        migrations.AlterModelOptions(
            name='streetarea',
            options={'verbose_name': 'Street Area', 'verbose_name_plural': '4.3. Street Areas'},
        ),
        migrations.AlterModelOptions(
            name='typechannel',
            options={'verbose_name': 'Type Channel', 'verbose_name_plural': '6. Type Channels'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='trend',
        ),
        migrations.AddField(
            model_name='channel',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Is popular'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.DeleteModel(
            name='Tariff',
        ),
    ]
