# Generated by Django 3.2.6 on 2021-09-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0008_auto_20210922_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typechannel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
    ]
