# Generated by Django 3.2.6 on 2021-09-22 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0009_alter_typechannel_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='porch',
        ),
        migrations.AlterField(
            model_name='channel',
            name='type_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='provider.typechannel', verbose_name='Type channel'),
        ),
    ]
