# Generated by Django 3.2.6 on 2021-10-01 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0010_auto_20210922_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homearea',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='provider.streetarea', verbose_name='Street'),
        ),
    ]
