# Generated by Django 3.2.6 on 2021-10-25 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0011_alter_homearea_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.homearea', verbose_name='Home'),
        ),
    ]
