# Generated by Django 3.2.6 on 2021-09-18 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='partner', verbose_name='Image')),
                ('title', models.CharField(max_length=50, verbose_name='Partner title')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='Partner title')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Partner title')),
                ('title_uz', models.CharField(max_length=50, null=True, verbose_name='Partner title')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Partner link')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='News title')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='News title')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='News title')),
                ('title_uz', models.CharField(max_length=50, null=True, verbose_name='News title')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
            options={
                'verbose_name': 'Trend',
                'verbose_name_plural': 'Trends',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='news', verbose_name='Image')),
                ('title', models.CharField(max_length=50, verbose_name='News title')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='News title')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='News title')),
                ('title_uz', models.CharField(max_length=50, null=True, verbose_name='News title')),
                ('content', models.TextField(verbose_name='Content')),
                ('content_en', models.TextField(null=True, verbose_name='Content')),
                ('content_ru', models.TextField(null=True, verbose_name='Content')),
                ('content_uz', models.TextField(null=True, verbose_name='Content')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('trend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.trend', verbose_name='Trends')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': "News'",
            },
        ),
    ]
