# Generated by Django 3.2.6 on 2021-09-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20210922_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='trend',
            field=models.IntegerField(choices=[(0, 'Internet'), (1, 'Telephony'), (2, 'IPTV'), (3, 'Camera'), (4, 'Device'), (5, 'Montage'), (6, 'Design'), (7, 'Development')], default=0, verbose_name='Trend'),
        ),
    ]
