# Generated by Django 3.2.6 on 2021-10-29 04:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_news_trend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Content'),
        ),
    ]
